name: CI
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Switch to Xcode 12
        run: sudo xcode-select -s /Applications/Xcode_12.app
      - name: Build
        env: 
          PROJECT: Xpendi.xcodeproj
          SCHEME: Xpendi (iOS)
          DESTINATION: platform=iOS Simulator,OS=14.0,name=iPhone 11
        run: |
          xcodebuild -project "$PROJECT" -scheme "$SCHEME" -destination "$DESTINATION" -configuration Release clean test CODE_SIGNING_ALLOWED=NO | xcpretty
